Preparing release v2.2.0

diff --git a/sagemaker_ssh_helper/sm-connect-ssh-proxy b/sagemaker_ssh_helper/sm-connect-ssh-proxy
--- a/sagemaker_ssh_helper/sm-connect-ssh-proxy
+++ b/sagemaker_ssh_helper/sm-connect-ssh-proxy
@@ -5,9 +5,19 @@
 # to the instance via S3 by executing the remote SSM command
 
 # Syntax:
-# sm-connect-ssh-proxy <instance_id> <s3_ssh_authorized_keys_path> <extra_ssh_args>
+# sm-connect-ssh-proxy [--silent-setup-only] <instance_id> <s3_ssh_authorized_keys_path> <extra_ssh_args>
 
 set -e
+set -o pipefail
+
+dir=$(dirname "$0")
+source "$dir"/sm-helper-functions 2>/dev/null || source sm-helper-functions
+
+silent_setup_only="false"
+if [[ "$1" == "--silent-setup-only" ]]; then
+  shift
+  silent_setup_only="true"
+fi
 
 INSTANCE_ID="$1"
 SSH_AUTHORIZED_KEYS_PATH="$2"
@@ -15,35 +25,56 @@ shift
 shift
 PORT_FWD_ARGS=$*
 
-echo "$(date -Iseconds) sm-connect-ssh-proxy: Connecting to: $INSTANCE_ID"
-echo "$(date -Iseconds) sm-connect-ssh-proxy: Extra args: $PORT_FWD_ARGS"
+s3_path_length=${#SSH_AUTHORIZED_KEYS_PATH}
+s3_path_last_char=${SSH_AUTHORIZED_KEYS_PATH:s3_path_length-1:1}
+[[ $s3_path_last_char != "/" ]] && SSH_AUTHORIZED_KEYS_PATH="$SSH_AUTHORIZED_KEYS_PATH/"
+
+if [[ "$silent_setup_only" == "false" ]]; then
+  echo "$(date -Iseconds) sm-connect-ssh-proxy: Connecting to: $INSTANCE_ID"
+  echo "$(date -Iseconds) sm-connect-ssh-proxy: Extra args: $PORT_FWD_ARGS"
+fi
 
 instance_status=$(aws ssm describe-instance-information --filters Key=InstanceIds,Values="$INSTANCE_ID" --query 'InstanceInformationList[0].PingStatus' --output text)
 
-echo "Instance status: $instance_status"
+if [[ "$silent_setup_only" == "false" ]]; then
+  echo "$(date -Iseconds) sm-connect-ssh-proxy: Instance status: $instance_status"
+fi
 
 if [[ "$instance_status" != "Online" ]]; then
-  echo "Error: Instance is offline."
+  echo "$(date -Iseconds) sm-connect-ssh-proxy: Error: Instance is offline."
   exit 1
 fi
 
-# TODO: make it possible to override the default (also helps avoid race conditions)
-SSH_KEY=~/.ssh/sagemaker-ssh-gw
+if [ -z "${SSH_KEY}" ]; then
+  SSH_KEY=~/.ssh/sagemaker-ssh-gw
+  echo "$(date -Iseconds) sm-connect-ssh-proxy: Generating $SSH_KEY keypair with ECDSA and uploading public key to $SSH_AUTHORIZED_KEYS_PATH"
+  echo 'yes' | ssh-keygen -t ecdsa -q -f "${SSH_KEY}" -N '' >/dev/null
+fi
 
-echo "Generating $SSH_KEY keypair with ECDSA and uploading public key to $SSH_AUTHORIZED_KEYS_PATH"
+SSH_KEY_NAME=$(basename "${SSH_KEY}")
+SSH_KEY_S3_PATH="${SSH_AUTHORIZED_KEYS_PATH}${SSH_KEY_NAME}"
 
-echo 'yes' | ssh-keygen -t ecdsa -q -f "${SSH_KEY}" -N '' >/dev/null
-aws s3 cp "${SSH_KEY}.pub" "${SSH_AUTHORIZED_KEYS_PATH}"
+if [[ "$silent_setup_only" == "false" ]]; then
+  aws s3 cp "${SSH_KEY}.pub" "${SSH_KEY_S3_PATH}.pub"
+else
+  aws s3 cp "${SSH_KEY}.pub" "${SSH_KEY_S3_PATH}.pub" >/dev/null
+fi
 
 CURRENT_REGION=$(aws configure list | grep region | awk '{print $2}')
-echo "Will use AWS Region: $CURRENT_REGION"
+if [[ "$silent_setup_only" == "false" ]]; then
+  echo "$(date -Iseconds) sm-connect-ssh-proxy: Will use AWS Region: $CURRENT_REGION"
+fi
 
 AWS_CLI_VERSION=$(aws --version)
-echo "AWS CLI version (should be v2): $AWS_CLI_VERSION"
+if [[ "$silent_setup_only" == "false" ]]; then
+  echo "$(date -Iseconds) sm-connect-ssh-proxy: AWS CLI version (should be v2): $AWS_CLI_VERSION"
+fi
 
 # TODO: consider moving to start-session with AWS-StartNonInteractiveCommand
 
-echo "Running SSM commands at region ${CURRENT_REGION} to copy public key to ${INSTANCE_ID}"
+if [[ "$silent_setup_only" == "false" ]]; then
+  echo "$(date -Iseconds) sm-connect-ssh-proxy: Running SSM commands at region ${CURRENT_REGION} to copy public key to ${INSTANCE_ID}"
+fi
 send_command=$(aws ssm send-command \
     --region "${CURRENT_REGION}" \
     --instance-ids "${INSTANCE_ID}" \
@@ -52,7 +83,7 @@ send_command=$(aws ssm send-command \
     --timeout-seconds 30 \
     --parameters "commands=[
         'mkdir -p /etc/ssh/authorized_keys.d/',
-        'aws s3 cp --recursive \"${SSH_AUTHORIZED_KEYS_PATH}\" /etc/ssh/authorized_keys.d/',
+        'aws s3 cp \"${SSH_KEY_S3_PATH}.pub\" /etc/ssh/authorized_keys.d/',
         'ls -la /etc/ssh/authorized_keys.d/',
         'cat /etc/ssh/authorized_keys.d/* > /etc/ssh/authorized_keys',
         'ls -la /etc/ssh/authorized_keys'
@@ -62,9 +93,11 @@ send_command=$(aws ssm send-command \
 
 json_value_regexp='s/^[^"]*".*": \"\(.*\)\"[^"]*/\1/'
 
-send_command=$(echo "$send_command" | python -m json.tool)
+send_command=$(echo "$send_command" | $(_python) -m json.tool)
 command_id=$(echo "$send_command" | grep "CommandId" | sed -e "$json_value_regexp")
-echo "Got command ID: $command_id"
+if [[ "$silent_setup_only" == "false" ]]; then
+  echo "$(date -Iseconds) sm-connect-ssh-proxy: Got command ID: $command_id"
+fi
 
 # Wait a little bit to prevent strange InvocationDoesNotExist error
 sleep 5
@@ -77,16 +110,22 @@ for i in $(seq 1 15); do
       --command-id "${command_id}" \
       --no-cli-pager --no-paginate \
       --output json)
-  command_output=$(echo "$command_output" | python -m json.tool)
+  command_output=$(echo "$command_output" | $(_python) -m json.tool)
   command_status=$(echo "$command_output" | grep '"Status":' | sed -e "$json_value_regexp")
   output_content=$(echo "$command_output" | grep '"StandardOutputContent":' | sed -e "$json_value_regexp")
   error_content=$(echo "$command_output" | grep '"StandardErrorContent":' | sed -e "$json_value_regexp")
 
-  echo "Command status: $command_status"
+  if [[ "$silent_setup_only" == "false" ]]; then
+    echo "$(date -Iseconds) sm-connect-ssh-proxy: Command status: $command_status ($i)"
+  fi
   if [[ "$command_status" != "Pending" && "$command_status" != "InProgress" ]]; then
-    echo "Command output: $output_content"
+    if [[ "$silent_setup_only" == "false" ]]; then
+      echo "$(date -Iseconds) sm-connect-ssh-proxy: Command output: $output_content"
+    fi
     if [[ "$error_content" != "" ]]; then
-      echo "Command error: $error_content"
+      if [[ "$silent_setup_only" == "false" ]]; then
+        echo "$(date -Iseconds) sm-connect-ssh-proxy: Command error: $error_content"
+      fi
     fi
     break
   fi
@@ -94,8 +133,13 @@ for i in $(seq 1 15); do
 done
 
 if [[ "$command_status" != "Success" ]]; then
-  echo "Error: Command didn't finish successfully in time"
+  echo "$(date -Iseconds) sm-connect-ssh-proxy: Error: Command didn't finish successfully in time"
   exit 2
+fi
+
+if [[ "$silent_setup_only" == "true" ]]; then
+  # Silent setup complete
+  exit 0
 fi
 
 echo "$(date -Iseconds) sm-connect-ssh-proxy: Starting SSH over SSM proxy"
@@ -113,6 +157,7 @@ proxy_command="aws ssm start-session\
 # shellcheck disable=SC2086
 ssh -4 -o User=root -o IdentityFile="${SSH_KEY}" -o IdentitiesOnly=yes \
   -o ProxyCommand="$proxy_command" \
+  -o ConnectTimeout=90 \
   -o ServerAliveInterval=15 -o ServerAliveCountMax=3 \
   -o PasswordAuthentication=no \
   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
diff --git a/sagemaker_ssh_helper/sm-helper-functions b/sagemaker_ssh_helper/sm-helper-functions
--- a/sagemaker_ssh_helper/sm-helper-functions
+++ b/sagemaker_ssh_helper/sm-helper-functions
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+function _python() {
+  if python3 --version 2>&1 | grep '^Python 3' >/dev/null 2>&1; then
+    echo "python3"
+  else
+    echo "python"
+  fi
+}
+
 function _silent_install() {
   install_path="/usr/local/bin"
 
@@ -34,13 +42,17 @@ function _is_macos() {
   uname | grep ^Darwin >/dev/null
 }
 
+function _is_windows() {
+  uname | grep ^MINGW >/dev/null
+}
+
 function _install_unzip() {
-  if _is_macos; then
+  if _is_macos || _is_windows; then
     :  # noop, should be already installed
   elif _is_centos; then
     sudo yum install -y unzip
   else
-    sudo apt-get install -y --no-install-recommends unzip
+    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends unzip
   fi
 }
 
@@ -61,7 +73,9 @@ function _install_aws_cli() {
   which pip >/dev/null 2>&1 && pip uninstall -y awscli
 
   # See: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
-  if _is_macos; then
+  if _is_windows; then
+    msiexec.exe //i https://awscli.amazonaws.com/AWSCLIV2.msi || echo "WARNING: msiexec.exe existed with non-zero code."
+  elif _is_macos; then
     _install_aws_cli_macos
   else
     _install_aws_cli_linux
@@ -107,22 +121,29 @@ function _install_session_manager_plugin_macos() {
   sudo ln -s /usr/local/sessionmanagerplugin/bin/session-manager-plugin /usr/local/bin/session-manager-plugin
 }
 
+function _install_session_manager_plugin_windows() {
+  curl -sS "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/windows/SessionManagerPluginSetup.exe" \
+    -o "/tmp/SessionManagerPluginSetup.exe"
+  /tmp/SessionManagerPluginSetup.exe || echo "Warning: SessionManagerPluginSetup.exe existed with non-zero code."
+}
+
 function _install_session_manager_plugin() {
   # See https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html
-  if _is_centos; then
+  if _is_windows; then
+    _install_session_manager_plugin_windows
+  elif _is_centos; then
     _install_session_manager_plugin_centos
   elif _is_macos; then
     _install_session_manager_plugin_macos
   else
     _install_session_manager_plugin_ubuntu
   fi
-  session-manager-plugin
 }
 
 
 
 function _install_curl_ubuntu() {
-  sudo apt-get install -y --no-install-recommends curl
+  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends curl
 }
 
 function _install_curl_centos() {
@@ -130,7 +151,7 @@ function _install_curl_centos() {
 }
 
 function _install_curl() {
-  if _is_macos; then
+  if _is_macos || _is_windows; then
     :  # noop, should be already installed
   elif _is_centos; then
     _install_curl_centos
@@ -169,6 +190,7 @@ function _print_sm_domain_id() {
 
 # shellcheck disable=SC2001
 function _print_sm_user_profile_name() {
+  # FIXME: Check for "SpaceName" - spaces are not supported yet
   sm_resource_metadata_json=$(tr -d "\n" < /opt/ml/metadata/resource-metadata.json)
   echo -n "$sm_resource_metadata_json" | sed -e 's/^.*"UserProfileName":\"\([^"]*\)\".*$/\1/'
 }
@@ -218,4 +240,47 @@ function _start_sshd() {
   else
     service ssh start || (echo "ERROR: Failed to start sshd service" && exit 255)
   fi
+}
+
+function _export_ssh_key_env_var() {
+  SM_SSH_HOST_NAME=$1
+  SSH_KEY=~/.ssh/${SM_SSH_HOST_NAME}
+  export SSH_KEY
+}
+
+function _check_ssh_proxy_host_name() {
+  SM_SSH_HOST_NAME=$1
+  SM_RESOURCE_TYPE=$2
+
+  if [[ "$SM_SSH_HOST_NAME" =~ ^.*\."$SM_RESOURCE_TYPE"\.sagemaker ]]; then
+    :
+  else
+    echo "sm-local-ssh-$SM_RESOURCE_TYPE: Error: Host name must end with '.$SM_RESOURCE_TYPE.sagemaker'"
+    exit 1
+  fi
+}
+
+function _generate_key_and_print_instance_id() {
+  SM_SSH_FQDN=$1
+  DOMAIN_ID=$2
+  USER_PROFILE_NAME=$3
+
+  if [[ -f $SSH_KEY ]]; then
+    # Don't generate again, or it will confuse SSH
+    # Only touch the file so it can be easily identified when you sort by last access timestamp
+    touch "$SSH_KEY"
+  else
+    # echo "Generating $SSH_KEY keypair with ECDSA and uploading public key to $SSH_AUTHORIZED_KEYS"
+    echo 'yes' | ssh-keygen -t ecdsa -q -f "${SSH_KEY}" -N '' >/dev/null
+  fi
+
+  # shellcheck disable=SC2091  # execute python location
+  $(_python) <<EOF
+import logging
+logging.basicConfig(level=logging.ERROR);
+logging.getLogger('sagemaker.config').setLevel(logging.WARNING)
+import sagemaker; from sagemaker_ssh_helper.wrapper import SSHEnvironmentWrapper;
+print(SSHEnvironmentWrapper.attach_to_resource("$SM_SSH_FQDN", "$DOMAIN_ID", "$USER_PROFILE_NAME").get_instance_id(timeout_in_sec=0));
+EOF
+
 }
diff --git a/sagemaker_ssh_helper/sm-init-ssm b/sagemaker_ssh_helper/sm-init-ssm
--- a/sagemaker_ssh_helper/sm-init-ssm
+++ b/sagemaker_ssh_helper/sm-init-ssm
@@ -8,11 +8,16 @@
 # The role for SSM is not a full IAM ARN, but only the last part of it such as 'service-role/SageMakerRole'
 
 set -e
+set -o pipefail
 
 dir=$(dirname "$0")
 source "$dir"/sm-helper-functions
 
 CURRENT_REGION=$(aws configure get region || echo "$AWS_REGION")
+if [ -z "${CURRENT_REGION}" ]; then
+  echo "ERROR: AWS Region cannot be determined. Try to run 'aws configure get region' manually and check the output."
+  exit 1
+fi
 
 SSH_CREATOR=$(aws sts get-caller-identity | jq --raw-output '.UserId')
 SSH_TIMESTAMP=$(date +%s)
@@ -31,7 +36,7 @@ elif [[ "$TRAINING_JOB_NAME" != "" ]]; then
   RESOURCE_ARN=$TRAINING_JOB_ARN  # empty for local mode
 elif [[ "$TRANSFORM_JOB_ARN" != "" ]]; then
   # Transform job
-  RESOURCE_NAME=$(echo $TRANSFORM_JOB_ARN | awk -F/ '{print $2}')
+  RESOURCE_NAME=$(echo "$TRANSFORM_JOB_ARN" | awk -F/ '{print $2}')
   RESOURCE_ARN=$TRANSFORM_JOB_ARN
 else
   # Probably, endpoint
diff --git a/sagemaker_ssh_helper/sm-local-configure b/sagemaker_ssh_helper/sm-local-configure
--- a/sagemaker_ssh_helper/sm-local-configure
+++ b/sagemaker_ssh_helper/sm-local-configure
@@ -1,16 +1,26 @@
 #!/bin/bash
 
+# Install locally AWS CLI and Session Manager Plugin
+# See: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
+# See: https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html
+
 set -e
+set -o pipefail
+
+_on_error() {
+  echo 'Error! Configuration is NOT complete.'
+}
+trap '_on_error' ERR
 
 dir=$(dirname "$0")
-source "$dir"/sm-helper-functions
+source "$dir"/sm-helper-functions 2>/dev/null || source sm-helper-functions
 
 uname -a
-cat /etc/issue || :
-cat /etc/os-release || :
+cat /etc/issue 2>/dev/null || echo "No /etc/issue file is present on the system."
+cat /etc/os-release 2>/dev/null || echo "No /etc/os-release is file present on the system."
 
 # Smoke test - Python version
-python3 --version
+$(_python) --version || echo "Error: No python3 is present on the system."
 
 echo "sm-local-configure: Installing tools. The 'sudo' commands can ask for your password."
 
@@ -20,6 +30,21 @@ _install_aws_cli
 
 echo "AWS default region - $AWS_DEFAULT_REGION"
 echo "AWS region - $AWS_REGION"
-aws configure list
+
+if _is_windows; then
+  echo "WARNING: Running on Windows. Restart your terminal app (e.g., Git Bash) "\
+    "and run 'aws configure list' manually, to verify the install"
+else
+  aws configure list
+fi
 
 _install_session_manager_plugin
+
+if _is_windows; then
+  echo "WARNING: Running on Windows. Restart your terminal app (e.g., Git Bash) "\
+    "and run 'session-manager-plugin' manually, to verify the install"
+else
+  session-manager-plugin
+fi
+
+echo "Configuration is complete!"
