Updated code to support ssh into sagemaker space apps - JupyterLab and
CodeEditor

1. Added Dockerfile to build custom image
2. Updated script to ssh into sagemaker space apps

diff --git a/sagemaker_ssh_helper/sm-helper-functions b/sagemaker_ssh_helper/sm-helper-functions
--- a/sagemaker_ssh_helper/sm-helper-functions
+++ b/sagemaker_ssh_helper/sm-helper-functions
@@ -194,9 +194,14 @@ function _print_sm_domain_id() {
 
 # shellcheck disable=SC2001
 function _print_sm_user_profile_name() {
-  # FIXME: Check for "SpaceName" - spaces are not supported yet
   sm_resource_metadata_json=$(tr -d "\n" < /opt/ml/metadata/resource-metadata.json)
-  echo -n "$sm_resource_metadata_json" | sed -e 's/^.*"UserProfileName":\"\([^"]*\)\".*$/\1/'
+  echo -n "$sm_resource_metadata_json" | jq -r '.UserProfileName'
+}
+
+# shellcheck disable=SC2001
+function _print_sm_space_name() {
+  sm_resource_metadata_json=$(tr -d "\n" < /opt/ml/metadata/resource-metadata.json)
+  echo -n "$sm_resource_metadata_json" | jq -r '.SpaceName'
 }
 
 function _print_sm_studio_python() {
@@ -242,7 +247,7 @@ function _start_sshd() {
   if _is_centos; then
     /usr/sbin/sshd
   else
-    service ssh start || (echo "ERROR: Failed to start sshd service" && exit 255)
+    sudo service ssh start || (echo "ERROR: Failed to start sshd service" && exit 255)
   fi
 }
 
diff --git a/sagemaker_ssh_helper/sm-local-ssh-ide b/sagemaker_ssh_helper/sm-local-ssh-ide
--- a/sagemaker_ssh_helper/sm-local-ssh-ide
+++ b/sagemaker_ssh_helper/sm-local-ssh-ide
@@ -39,6 +39,7 @@ echo "sm-local-ssh-ide: Starting in $dir"
 
 DOMAIN_ID=""
 USER_PROFILE_NAME=""
+SPACE_NAME=""
 
 if [[ "$1" == "--domain-id" ]]; then
     DOMAIN_ID=$2
@@ -68,6 +69,12 @@ if [[ "$COMMAND" != "set-user-profile-name" && "$COMMAND" != "set-domain-id" \
     echo "sm-local-ssh-ide: WARNING: SageMaker Studio user profile name is not set."\
       "Run 'sm-local-ssh-ide set-user-profile-name' to override."
   fi
+  if [ -f ~/.sm-studio-space-name ]; then
+    SPACE_NAME="$(cat ~/.sm-studio-space-name)"
+  else
+    echo "sm-local-ssh-ide: WARNING: SageMaker Studio space name is not set."\
+      "Run 'sm-local-ssh-ide set-space-name' to override."
+  fi
 fi
 
 if [[ "$COMMAND" == "proxy-host" ]]; then
@@ -87,12 +94,21 @@ elif [[ "$COMMAND" == "connect-app" ]]; then
   OPTIONS="$3"
 
   # shellcheck disable=SC2091
-  INSTANCE_ID=$($(_python) <<EOF
-import sagemaker; from sagemaker_ssh_helper.ide import SSHIDE;
-import logging; logging.basicConfig(level=logging.INFO);
-SSHIDE("$DOMAIN_ID", "$USER_PROFILE_NAME").print_kernel_instance_id("$SM_STUDIO_KGW_NAME", timeout_in_sec=300)
-EOF
-  )
+  if [ -z "$SPACE_NAME" ]; then
+      INSTANCE_ID=$(python <<EOF
+  import sagemaker; from sagemaker_ssh_helper.ide import SSHIDE;
+  import logging; logging.basicConfig(level=logging.INFO);
+  SSHIDE("$DOMAIN_ID", "$USER_PROFILE_NAME").print_kernel_instance_id("$SM_STUDIO_KGW_NAME", timeout_in_sec=300)
+  EOF
+    )
+    else
+      INSTANCE_ID=$(python <<EOF
+  import sagemaker; from sagemaker_ssh_helper.ide import SSHIDE;
+  import logging; logging.basicConfig(level=logging.INFO);
+  SSHIDE("$DOMAIN_ID", "$USER_PROFILE_NAME", space="$SPACE_NAME").print_space_instance_id("$SM_STUDIO_KGW_NAME", timeout_in_sec=300)
+  EOF
+    )
+  fi
 
   if [[ "$OPTIONS" == "--ssh-only" ]]; then
     echo "sm-local-ssh-ide: Connecting only SSH to local port 10022 (got the flag --ssh-only)"
@@ -140,6 +156,15 @@ elif [[ "$COMMAND" == "set-user-profile-name" ]]; then
     fi
     echo "sm-local-ssh-ide: Saving SageMaker Studio user profile name into ~/.sm-studio-user-profile-name"
     echo "$USER_PROFILE_NAME" > ~/.sm-studio-user-profile-name
+
+elif [[ "$COMMAND" == "set-space-name" ]]; then
+    SPACE_NAME="$(echo "$2" | tr '[:upper:]' '[:lower:]')"
+    if [[ "$SPACE_NAME" == "" ]]; then
+      echo "sm-local-ssh-ide: ERROR: <space-name> argument is expected"
+      exit 1
+    fi
+    echo "sm-local-ssh-ide: Saving SageMaker Studio user profile name into ~/.sm-studio-space-name"
+    echo "$SPACE_NAME" > ~/.sm-studio-space-name
 
 elif [[ "$COMMAND" == "run-command" ]]; then
 
