sm-local-* scripts API refactoring to support extended sm-ssh CLI syntax

diff --git a/sagemaker_ssh_helper/sm-local-ssh-ide b/sagemaker_ssh_helper/sm-local-ssh-ide
--- a/sagemaker_ssh_helper/sm-local-ssh-ide
+++ b/sagemaker_ssh_helper/sm-local-ssh-ide
@@ -4,8 +4,8 @@
 # Run `sm-ssh -h` for the high-level interface.
 
 # Commands:
-# [--domain-id <domain-id>] [--user-profile-name <user-profile-name>] connect <app_name> [--ssh-only] [<extra_ssh_args>]
-# [--domain-id <domain-id>] [--user-profile-name <user-profile-name>] start-proxy <app_name>
+# [--domain-id <domain-id>] [--user-profile-name <user-profile-name>] connect-app <app_name> [--ssh-only] [<extra_ssh_args>]
+# [--domain-id <domain-id>] [--user-profile-name <user-profile-name>] proxy-host <fqdn>
 # run-command <command> <args...>
 # set-domain-id <domain_id>
 # set-user-profile-name <user_profile_name>
@@ -34,6 +34,8 @@ trap '_on_error' ERR
 self=$(realpath "${BASH_SOURCE[0]}")
 dir=$(dirname "$self")
 source "$dir"/sm-helper-functions 2>/dev/null || source sm-helper-functions
+
+echo "sm-local-ssh-ide: Starting in $dir"
 
 DOMAIN_ID=""
 USER_PROFILE_NAME=""
@@ -68,7 +70,7 @@ if [[ "$COMMAND" != "set-user-profile-name" && "$COMMAND" != "set-domain-id" \
   fi
 fi
 
-if [[ "$COMMAND" == "start-proxy" ]]; then
+if [[ "$COMMAND" == "proxy-host" ]]; then
   SM_SSH_HOST_NAME="$2"
   SM_RESOURCE_TYPE="studio"
 
@@ -79,7 +81,7 @@ if [[ "$COMMAND" == "start-proxy" ]]; then
 
   sm-local-start-ssh --proxy-setup-only "${INSTANCE_ID}"
 
-elif [[ "$COMMAND" == "connect" ]]; then
+elif [[ "$COMMAND" == "connect-app" ]]; then
 
   SM_STUDIO_KGW_NAME="$2"
   OPTIONS="$3"
@@ -150,9 +152,6 @@ elif [[ "$COMMAND" == "run-command" ]]; then
     $ARGS
 
 else
-    echo "Deprecated warning: sm-local-ssh-ide <kernel_gateway_name> is deprecated and will be removed in future versions, use sm-local-ssh-ide connect <kernel_gateway_name> instead"
-    echo "Re-trying with the 'connect' argument:"
-    echo "sm-local-ssh-ide connect $*"
-    # shellcheck disable=SC2048
-    $0 connect $*
+    echo "ERROR: Unknown command: '$COMMAND'"
+    exit 1
 fi
diff --git a/sagemaker_ssh_helper/sm-local-ssh-inference b/sagemaker_ssh_helper/sm-local-ssh-inference
--- a/sagemaker_ssh_helper/sm-local-ssh-inference
+++ b/sagemaker_ssh_helper/sm-local-ssh-inference
@@ -4,7 +4,8 @@
 # Run `sm-ssh -h` for the high-level interface.
 
 # Commands:
-# connect <endpoint_name> [<extra_ssh_args>]
+# connect-endpoint <endpoint_name> [<extra_ssh_args>]
+# proxy-host <fqdn>
 # stop-waiting
 # run-command <command> <args...>
 
@@ -15,9 +16,12 @@ self=$(realpath "${BASH_SOURCE[0]}")
 dir=$(dirname "$self")
 source "$dir"/sm-helper-functions 2>/dev/null || source sm-helper-functions
 
+echo "sm-local-ssh-inference: Starting in $dir"
+
+
 COMMAND=$1
 
-if [[ "$COMMAND" == "start-proxy" ]]; then
+if [[ "$COMMAND" == "proxy-host" ]]; then
   SM_SSH_HOST_NAME="$2"
   SM_RESOURCE_TYPE="inference"
 
@@ -28,7 +32,7 @@ if [[ "$COMMAND" == "start-proxy" ]]; then
 
   sm-local-start-ssh --proxy-setup-only "${INSTANCE_ID}"
 
-elif [[ "$COMMAND" == "connect" ]]; then
+elif [[ "$COMMAND" == "connect-endpoint" ]]; then
   ENDPOINT_NAME=$2
 
   # shellcheck disable=SC2091
@@ -62,5 +66,6 @@ elif [[ "$COMMAND" == "run-command" ]]; then
     $ARGS
 
 else
-    echo "Unknown command: $COMMAND"
+    echo "ERROR: Unknown command: '$COMMAND'"
+    exit 1
 fi
diff --git a/sagemaker_ssh_helper/sm-local-ssh-notebook b/sagemaker_ssh_helper/sm-local-ssh-notebook
--- a/sagemaker_ssh_helper/sm-local-ssh-notebook
+++ b/sagemaker_ssh_helper/sm-local-ssh-notebook
@@ -4,7 +4,8 @@
 # Run `sm-ssh -h` for the high-level interface.
 
 # Commands:
-# connect <notebook-instance-name> [<extra_ssh_args>]
+# connect-notebook <notebook-instance-name> [<extra_ssh_args>]
+# proxy-host <fqdn>
 # run-command <command> <args...>
 
 set -e
@@ -14,9 +15,11 @@ self=$(realpath "${BASH_SOURCE[0]}")
 dir=$(dirname "$self")
 source "$dir"/sm-helper-functions 2>/dev/null || source sm-helper-functions
 
+echo "sm-local-ssh-notebook: Starting in $dir"
+
 COMMAND=$1
 
-if [[ "$COMMAND" == "start-proxy" ]]; then
+if [[ "$COMMAND" == "proxy-host" ]]; then
   SM_SSH_HOST_NAME="$2"
   SM_RESOURCE_TYPE="notebook"
 
@@ -27,7 +30,7 @@ if [[ "$COMMAND" == "start-proxy" ]]; then
 
   sm-local-start-ssh --proxy-setup-only "${INSTANCE_ID}"
 
-elif [[ "$COMMAND" == "connect" ]]; then
+elif [[ "$COMMAND" == "connect-notebook" ]]; then
 
   NOTEBOOK_INSTANCE_NAME="$2"
 
@@ -56,5 +59,6 @@ elif [[ "$COMMAND" == "run-command" ]]; then
     $ARGS
 
 else
-    echo "Unknown command: $COMMAND"
+    echo "ERROR: Unknown command: '$COMMAND'"
+    exit 1
 fi
diff --git a/sagemaker_ssh_helper/sm-local-ssh-processing b/sagemaker_ssh_helper/sm-local-ssh-processing
--- a/sagemaker_ssh_helper/sm-local-ssh-processing
+++ b/sagemaker_ssh_helper/sm-local-ssh-processing
@@ -4,7 +4,8 @@
 # Run `sm-ssh -h` for the high-level interface.
 
 # Commands:
-# connect <processing_job_name> [<extra_ssh_args>]
+# connect-job <processing_job_name> [<extra_ssh_args>]
+# proxy-host <fqdn>
 # stop-waiting
 # run-command <command> <args...>
 
@@ -15,9 +16,11 @@ self=$(realpath "${BASH_SOURCE[0]}")
 dir=$(dirname "$self")
 source "$dir"/sm-helper-functions 2>/dev/null || source sm-helper-functions
 
+echo "sm-local-ssh-processing: Starting in $dir"
+
 COMMAND=$1
 
-if [[ "$COMMAND" == "start-proxy" ]]; then
+if [[ "$COMMAND" == "proxy-job" ]]; then
   SM_SSH_HOST_NAME="$2"
   SM_RESOURCE_TYPE="processing"
 
@@ -28,7 +31,7 @@ if [[ "$COMMAND" == "start-proxy" ]]; then
 
   sm-local-start-ssh --proxy-setup-only "${INSTANCE_ID}"
 
-elif [[ "$COMMAND" == "connect" ]]; then
+elif [[ "$COMMAND" == "connect-job" ]]; then
   JOB_NAME=$2
 
   # shellcheck disable=SC2091
@@ -61,5 +64,6 @@ elif [[ "$COMMAND" == "run-command" ]]; then
     $ARGS
 
 else
-    echo "Unknown command: $COMMAND"
+    echo "ERROR: Unknown command: '$COMMAND'"
+    exit 1
 fi
