Support both user profile and space seamlessly

diff --git a/sagemaker_ssh_helper/sm-local-ssh-ide b/sagemaker_ssh_helper/sm-local-ssh-ide
--- a/sagemaker_ssh_helper/sm-local-ssh-ide
+++ b/sagemaker_ssh_helper/sm-local-ssh-ide
@@ -4,11 +4,11 @@
 # Run `sm-ssh -h` for the high-level interface.
 
 # Commands:
-# [--domain-id <domain-id>] [--user-profile-name <user-profile-name>] connect-app <app_name> [--ssh-only] [<extra_ssh_args>]
-# [--domain-id <domain-id>] [--user-profile-name <user-profile-name>] proxy-host <fqdn>
+# [--domain-id <domain-id>] [--user-profile-or-space-name <user-profile-or-space-name>] connect-app <app_name> [--ssh-only] [<extra_ssh_args>]
+# [--domain-id <domain-id>] [--user-profile-or-space-name <user-profile-or-space-name>] proxy-host <fqdn>
 # run-command <command> <args...>
 # set-domain-id <domain_id>
-# set-user-profile-name <user_profile_name>
+# set-user-profile-or-space-name <user_profile_or_space_name>
 # set-jb-license-server <jb-license-server-hostname-without-http>
 
 # SageMaker Studio app name for Kernel Gateways is usually the same as the hostname,
@@ -16,7 +16,7 @@
 # For JupyterServer app it's 'default'.
 
 # Tip: to open SageMaker Studio UI in Firefox from command line on macOS, use the following command:
-# open -a Firefox $(AWS_PROFILE=terry aws sagemaker create-presigned-domain-url --domain-id d-lnwlaexample --user-profile-name terry-whitlock --query AuthorizedUrl --output text)
+# open -a Firefox $(AWS_PROFILE=terry aws sagemaker create-presigned-domain-url --domain-id d-lnwlaexample --user-profile-or-space-name terry-whitlock --query AuthorizedUrl --output text)
 
 
 # replace with your JetBrains License Server host, or leave it as is if you don't use one
@@ -38,8 +38,7 @@ source "$dir"/sm-helper-functions 2>/dev/null || source sm-helper-functions
 echo "sm-local-ssh-ide: Starting in $dir"
 
 DOMAIN_ID=""
-USER_PROFILE_NAME=""
-SPACE_NAME=""
+USER_PROFILE_OR_SPACE_NAME=""
 
 if [[ "$1" == "--domain-id" ]]; then
     DOMAIN_ID=$2
@@ -47,39 +46,27 @@ if [[ "$1" == "--domain-id" ]]; then
     shift
 fi
 
-if [[ "$1" == "--user-profile-name" ]]; then
-    USER_PROFILE_NAME=$2
-    shift
-    shift
-fi
-
-if [[ "$1" == "--space-name" ]]; then
-    SPACE_NAME=$2
+if [[ "$1" == "--user-profile-or-space-name" ]]; then
+    USER_PROFILE_OR_SPACE_NAME=$2
     shift
     shift
 fi
 
 COMMAND=$1
 
-if [[ "$COMMAND" != "set-user-profile-name" && "$COMMAND" != "set-domain-id" \
-      && "$DOMAIN_ID" == "" && "$USER_PROFILE_NAME" == "" ]]; then
+if [[ "$COMMAND" != "set-user-profile-or-space-name" && "$COMMAND" != "set-domain-id" \
+      && "$DOMAIN_ID" == "" && "$USER_PROFILE_OR_SPACE_NAME" == "" ]]; then
   if [ -f ~/.sm-studio-domain-id ]; then
     DOMAIN_ID="$(cat ~/.sm-studio-domain-id)"
   else
     echo "sm-local-ssh-ide: WARNING: SageMaker Studio domain ID is not set."\
       "Run 'sm-local-ssh-ide set-domain-id' to override."
   fi
-  if [ -f ~/.sm-studio-user-profile-name ]; then
-    USER_PROFILE_NAME="$(cat ~/.sm-studio-user-profile-name)"
+  if [ -f ~/.sm-studio-user-profile-or-space-name ]; then
+    USER_PROFILE_OR_SPACE_NAME="$(cat ~/.sm-studio-user-profile-or-space-name)"
   else
     echo "sm-local-ssh-ide: WARNING: SageMaker Studio user profile name is not set."\
-      "Run 'sm-local-ssh-ide set-user-profile-name' to override."
-  fi
-  if [ -f ~/.sm-studio-space-name ]; then
-    SPACE_NAME="$(cat ~/.sm-studio-space-name)"
-  else
-    echo "sm-local-ssh-ide: WARNING: SageMaker Studio space name is not set."\
-      "Run 'sm-local-ssh-ide set-space-name' to override."
+      "Run 'sm-local-ssh-ide set-user-profile-or-space-name' to override."
   fi
 fi
 
@@ -90,31 +77,31 @@ if [[ "$COMMAND" == "proxy-host" ]]; then
   _check_ssh_proxy_host_name "$SM_SSH_HOST_NAME" "$SM_RESOURCE_TYPE"
   _export_ssh_key_env_var "$SM_SSH_HOST_NAME"
 
-  INSTANCE_ID=$(_generate_key_and_print_instance_id "$SM_SSH_HOST_NAME" "$DOMAIN_ID" "$USER_PROFILE_NAME")
+  INSTANCE_ID=$(_generate_key_and_print_instance_id "$SM_SSH_HOST_NAME" "$DOMAIN_ID" "$USER_PROFILE_OR_SPACE_NAME")
 
   sm-local-start-ssh --proxy-setup-only "${INSTANCE_ID}"
 
-elif [[ "$COMMAND" == "connect-app" ]]; then
-
-  SM_STUDIO_KGW_NAME="$2"
+elif [[ "$COMMAND" == connect* ]]; then
+  SM_STUDIO_APP_NAME="$2"
   OPTIONS="$3"
 
-  # shellcheck disable=SC2091
-  if [ -z "$SPACE_NAME" ]; then
-    INSTANCE_ID=$(python <<EOF
-import sagemaker; from sagemaker_ssh_helper.ide import SSHIDE;
-import logging; logging.basicConfig(level=logging.INFO);
-SSHIDE("$DOMAIN_ID", "$USER_PROFILE_NAME").print_kernel_instance_id("$SM_STUDIO_KGW_NAME", timeout_in_sec=300)
-EOF
-    )
-    else
-    INSTANCE_ID=$(python <<EOF
-import sagemaker; from sagemaker_ssh_helper.ide import SSHIDE;
-import logging; logging.basicConfig(level=logging.INFO);
-SSHIDE("$DOMAIN_ID", "$USER_PROFILE_NAME", space="$SPACE_NAME").print_space_instance_id("$SM_STUDIO_KGW_NAME", timeout_in_sec=300)
-EOF
-    )
+  if [[ "$COMMAND" == "connect-app" ]]; then
+    IS_USER_PROFILE="True"
+  elif [[ "$COMMAND" == "connect-space-app" ]]; then
+    IS_USER_PROFILE="False"
+  else
+    echo "ERROR: Unknown command: '$COMMAND'"
+    exit 1
   fi
+
+  # shellcheck disable=SC2091
+  INSTANCE_ID=$($(_python) <<EOF
+import sagemaker; from sagemaker_ssh_helper.ide import SSHIDE;
+import logging; logging.basicConfig(level=logging.INFO);
+SSHIDE("$DOMAIN_ID", user_or_space="$USER_PROFILE_OR_SPACE_NAME", is_user_profile=$IS_USER_PROFILE).print_instance_id("$SM_STUDIO_APP_NAME", timeout_in_sec=300)
+EOF
+    )
+  echo "${INSTANCE_ID}"
 
   if [[ "$OPTIONS" == "--ssh-only" ]]; then
     echo "sm-local-ssh-ide: Connecting only SSH to local port 10022 (got the flag --ssh-only)"
@@ -138,6 +125,7 @@ EOF
         -R 127.0.0.1:443:"$JB_LICENSE_SERVER_HOST":443 \
         $*
   fi
+fi
 
 elif [[ "$COMMAND" == "set-jb-license-server" ]]; then
     JB_LICENSE_SERVER_HOST="$2"
@@ -154,23 +142,14 @@ elif [[ "$COMMAND" == "set-domain-id" ]]; then
     echo "sm-local-ssh-ide: Saving SageMaker Studio domain ID into ~/.sm-studio-domain-id"
     echo "$DOMAIN_ID" > ~/.sm-studio-domain-id
 
-elif [[ "$COMMAND" == "set-user-profile-name" ]]; then
-    USER_PROFILE_NAME="$2"
-    if [[ "$USER_PROFILE_NAME" == "" ]]; then
-      echo "sm-local-ssh-ide: ERROR: <user-profile-name> argument is expected"
+elif [[ "$COMMAND" == "set-user-profile-or-space-name" ]]; then
+    USER_PROFILE_OR_SPACE_NAME="$2"
+    if [[ "$USER_PROFILE_OR_SPACE_NAME" == "" ]]; then
+      echo "sm-local-ssh-ide: ERROR: <user-profile-or-space-name> argument is expected"
       exit 1
     fi
-    echo "sm-local-ssh-ide: Saving SageMaker Studio user profile name into ~/.sm-studio-user-profile-name"
-    echo "$USER_PROFILE_NAME" > ~/.sm-studio-user-profile-name
-
-elif [[ "$COMMAND" == "set-space-name" ]]; then
-    SPACE_NAME="$(echo "$2" | tr '[:upper:]' '[:lower:]')"
-    if [[ "$SPACE_NAME" == "" ]]; then
-      echo "sm-local-ssh-ide: ERROR: <space-name> argument is expected"
-      exit 1
-    fi
-    echo "sm-local-ssh-ide: Saving SageMaker Studio user profile name into ~/.sm-studio-space-name"
-    echo "$SPACE_NAME" > ~/.sm-studio-space-name
+    echo "sm-local-ssh-ide: Saving SageMaker Studio user profile name into ~/.sm-studio-user-profile-or-space-name"
+    echo "$USER_PROFILE_OR_SPACE_NAME" > ~/.sm-studio-user-profile-or-space-name
 
 elif [[ "$COMMAND" == "run-command" ]]; then
 
