Adding syslog logging to troubleshoot sshd issues and support for locales in Debian

diff --git a/sagemaker_ssh_helper/sm-setup-ssh b/sagemaker_ssh_helper/sm-setup-ssh
--- a/sagemaker_ssh_helper/sm-setup-ssh
+++ b/sagemaker_ssh_helper/sm-setup-ssh
@@ -30,13 +30,21 @@ if [[ "$1" == "configure" ]]; then
 
   echo "Installing SSH server and auxiliary tools"
   if _is_centos; then
-    yum install -y openssh-server net-tools procps less jq vim rsync perl
+    yum install -y openssh-server net-tools procps less jq vim rsync perl rsyslog
   else
     export DEBIAN_FRONTEND=noninteractive
     apt-get -qq update || echo 'sm-ssh-ide: WARNING - issues with retrieving new lists of packages'
     apt-get -qq -y install apt-utils
-    apt-get -qq -y install ssh net-tools procps less jq vim rsync
+    apt-get -qq -y install ssh net-tools procps less jq vim rsync locales rsyslog
+
+    # Install some locales to work with UTF-8 charsets
+    echo "C.UTF-8 UTF-8" >> /etc/locale.gen
+    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
   fi
+
+  # Sending all system logs to CloudWatch (helps to troubleshoot sshd issues)
+  find /etc/rsyslog.conf /etc/rsyslog.d/ -type f \
+    -exec sed -i -e 's~/var/log/~/var/log/apps/app_container.log__~' {} \;
 
   sed -i -e 's~^ClientAliveInterval~#ClientAliveInterval~' /etc/ssh/sshd_config
   echo "ClientAliveInterval 15" >> /etc/ssh/sshd_config
@@ -94,13 +102,22 @@ if [[ "$1" == "start-ssh" ]]; then
   # Dump container bootstrap environment (PID 1) - can be different from above, useful for debugging
   ps wwwe -p 1 | tail -1
 
+  if _is_centos; then
+    :
+  else
+    # Generating UTF-8 locales for Debian
+    locale-gen
+  fi
+
   # Start SSH server
   if _is_centos; then
     # NOTE: systemctl will not work in CentOS SageMaker container (e.g. Spark processing) because lack of
     # privileges to access DBUS, so we run sshd manually. This command doesn't work:
-    # # service sshd start || (echo "ERROR: Failed to start sshd service" && exit 255)
+    # systemctl start sshd
+    /usr/sbin/rsyslogd
     /usr/sbin/sshd
   else
+    service rsyslog start || (echo "ERROR: Failed to start syslogd service")
     service ssh start || (echo "ERROR: Failed to start ssh service" && exit 255)
   fi
 
diff --git a/sagemaker_ssh_helper/sm-ssh-ide b/sagemaker_ssh_helper/sm-ssh-ide
--- a/sagemaker_ssh_helper/sm-ssh-ide
+++ b/sagemaker_ssh_helper/sm-ssh-ide
@@ -67,6 +67,11 @@ EOF
 
 elif [[ "$1" == "get-metadata" ]]; then
 
+  if [[ ! -f /opt/ml/metadata/resource-metadata.json ]]; then
+    echo "sm-ssh-ide: ERROR: must be running inside SageMaker Studio"
+    exit 2
+  fi
+
   echo "App name: $(_print_sm_app_name)"
   echo "User profile name: $(_print_sm_user_profile_name)"
   echo "Domain: $(_print_sm_domain_id)"
